package com.bng.core.entity;

// Generated 25 Mar, 2014 12:37:23 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ContentPlaylistMapper generated by hbm2java
 */
@Entity
@Table(name = "content_playlist_mapper")
public class ContentPlaylistMapper implements java.io.Serializable {

	private Integer id;
	private Content content;
	private ContentPlaylist contentPlaylist;

	public ContentPlaylistMapper() {
	}

	public ContentPlaylistMapper(Content content,
			ContentPlaylist contentPlaylist) {
		this.content = content;
		this.contentPlaylist = contentPlaylist;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "content_id", nullable = false)
	public Content getContent() {
		return this.content;
	}

	public void setContent(Content content) {
		this.content = content;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "playlist_id", nullable = false)
	public ContentPlaylist getContentPlaylist() {
		return this.contentPlaylist;
	}

	public void setContentPlaylist(ContentPlaylist contentPlaylist) {
		this.contentPlaylist = contentPlaylist;
	}

}
