package com.bng.core.entity;

// Generated 25 Mar, 2014 12:37:23 PM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Content generated by hbm2java
 */
@Entity
@Table(name = "content")
public class Content implements java.io.Serializable {

	private Integer id;
	private String path;
	private String type;
	private Date createdDate;
	private Date expiredate;
	private Set<ContentMeta> contentMetas = new HashSet<ContentMeta>(0);
	private Set<ContentMapper> contentMappers = new HashSet<ContentMapper>(0);
	private Set<ContentPlaylistMapper> contentPlaylistMappers = new HashSet<ContentPlaylistMapper>(
			0);

	public Content() {
	}

	public Content(String path, String type, Date createdDate, Date expiredate,
			Set<ContentMeta> contentMetas, Set<ContentMapper> contentMappers,
			Set<ContentPlaylistMapper> contentPlaylistMappers) {
		this.path = path;
		this.type = type;
		this.createdDate = createdDate;
		this.expiredate = expiredate;
		this.contentMetas = contentMetas;
		this.contentMappers = contentMappers;
		this.contentPlaylistMappers = contentPlaylistMappers;
	}

     public Content(String path, String type, Date createdDate, Date expiredate) 
     {
      this.path = path;
      this.type = type;
      this.createdDate = createdDate;
      this.expiredate = expiredate;      
     }
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "path", length = 2000, unique=true)
	public String getPath() {
		return this.path;
	}

	public void setPath(String path) {
		this.path = path;
	}

	@Column(name = "type")
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_date", length = 19)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "expiredate", length = 19)
	public Date getExpiredate() {
		return this.expiredate;
	}

	public void setExpiredate(Date expiredate) {
		this.expiredate = expiredate;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "content")
	public Set<ContentMeta> getContentMetas() {
		return this.contentMetas;
	}

	public void setContentMetas(Set<ContentMeta> contentMetas) {
		this.contentMetas = contentMetas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "content")
	public Set<ContentMapper> getContentMappers() {
		return this.contentMappers;
	}

	public void setContentMappers(Set<ContentMapper> contentMappers) {
		this.contentMappers = contentMappers;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "content")
	public Set<ContentPlaylistMapper> getContentPlaylistMappers() {
		return this.contentPlaylistMappers;
	}

	public void setContentPlaylistMappers(
			Set<ContentPlaylistMapper> contentPlaylistMappers) {
		this.contentPlaylistMappers = contentPlaylistMappers;
	}

}
