package com.bng.core.entity;

// Generated 25 Mar, 2014 12:37:23 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ContentPlaylist generated by hbm2java
 */
@Entity
@Table(name = "content_playlist")
public class ContentPlaylist implements java.io.Serializable {

	private Integer id;
	private String playlistName;
	private Set<ContentPlaylistMapper> contentPlaylistMappers = new HashSet<ContentPlaylistMapper>(
			0);

	public ContentPlaylist() {
	}

	public ContentPlaylist(String playlistName) {
		this.playlistName = playlistName;
	}

	public ContentPlaylist(String playlistName,
			Set<ContentPlaylistMapper> contentPlaylistMappers) {
		this.playlistName = playlistName;
		this.contentPlaylistMappers = contentPlaylistMappers;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "playlist_name", nullable = false, length = 50)
	public String getPlaylistName() {
		return this.playlistName;
	}

	public void setPlaylistName(String playlistName) {
		this.playlistName = playlistName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "contentPlaylist")
	public Set<ContentPlaylistMapper> getContentPlaylistMappers() {
		return this.contentPlaylistMappers;
	}

	public void setContentPlaylistMappers(
			Set<ContentPlaylistMapper> contentPlaylistMappers) {
		this.contentPlaylistMappers = contentPlaylistMappers;
	}

}
