package com.bng.core.entity;

// default package
// Generated Dec 3, 2013 5:04:20 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * MxgraphKeyMapping generated by hbm2java
 */
@Entity
@Table(name = "mxgraph_key_mapping")
public class MxgraphKeyMapping implements java.io.Serializable {

	private Integer id;
	private Mxgraph mxgraph;
	private String shortcode;

	public MxgraphKeyMapping() {
	}

	public MxgraphKeyMapping(Mxgraph mxgraph, String shortcode) {
		this.mxgraph = mxgraph;
		this.shortcode = shortcode;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "mxgraph_id", nullable = false)
	public Mxgraph getMxgraph() {
		return this.mxgraph;
	}

	public void setMxgraph(Mxgraph mxgraph) {
		this.mxgraph = mxgraph;
	}

	@Column(name = "shortcode", nullable = false, length = 15)
	public String getShortcode() {
		return this.shortcode;
	}

	public void setShortcode(String shortcode) {
		this.shortcode = shortcode;
	}

}
