package com.bng.core.entity;
// Generated Sep 30, 2013 11:56:12 AM by Hibernate Tools 3.2.1.GA


import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Operator generated by hbm2java
 */
@Entity
@Table(name="operator")
public class Operator  implements java.io.Serializable {


     private Integer id;
     private String operatorName;
     private Set<UserMapping> userMapping = new HashSet<UserMapping>(0);

    public Operator() {
    }

    public Operator(String operatorName, Set<UserMapping> userMapping) {
       this.operatorName = operatorName;
       this.userMapping = userMapping;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    
    @Column(name="Operator_name")
    public String getOperatorName() {
        return this.operatorName;
    }
    
    public void setOperatorName(String operatorName) {
        this.operatorName = operatorName;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="operator")
    public Set<UserMapping> getUserMapping() {
        return this.userMapping;
    }
    
    public void setUserMapping(Set<UserMapping> userMapping) {
        this.userMapping = userMapping;
    }




}


