package com.bng.core.entity;
// Generated Sep 30, 2013 11:56:12 AM by Hibernate Tools 3.2.1.GA


import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * UrlAccess generated by hbm2java
 */
@Entity
@Table(name="url_access"
)
public class UrlAccess  implements java.io.Serializable {


     private Integer id;
     private String access;
     private String url;

    public UrlAccess() {
    }

    public UrlAccess(String access, String url) {
       this.access = access;
       this.url = url;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    
    @Column(name="ACCESS", length=50)
    public String getAccess() {
        return this.access;
    }
    
    public void setAccess(String access) {
        this.access = access;
    }
    
    @Column(name="URL", length=100)
    public String getUrl() {
        return this.url;
    }
    
    public void setUrl(String url) {
        this.url = url;
    }




}


