package com.bng.core.entity;
// Generated Sep 30, 2013 11:56:12 AM by Hibernate Tools 3.2.1.GA


import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * UserRoless generated by hbm2java
 */
@Entity
@Table(name="user_roless")
public class UserRoless  implements java.io.Serializable {


     private Integer id;
     private Userss userss;
     private String authority;

    public UserRoless() {
    }

	
    public UserRoless(Userss userss) {
        this.userss = userss;
    }
    public UserRoless(Userss userss, String authority) {
       this.userss = userss;
       this.authority = authority;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="Id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="user_id", nullable=false)
    public Userss getUserss() {
        return this.userss;
    }
    
    public void setUserss(Userss userss) {
        this.userss = userss;
    }
    
    @Column(name="authority")
    public String getAuthority() {
        return this.authority;
    }
    
    public void setAuthority(String authority) {
        this.authority = authority;
    }




}


