package com.bng.core.entity;
// Generated Sep 30, 2013 11:56:12 AM by Hibernate Tools 3.2.1.GA


import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Users generated by hbm2java
 */
@Entity
@Table(name="users")
public class Users  implements java.io.Serializable {


     private Integer id;
     private String username;
     private String password;
     private Integer status;
     private Set<UserMapping> userMapping = new HashSet<UserMapping>(0);
     private Set<UserRoles> userRoles = new HashSet<UserRoles>(0);

    public Users() {
    }

    public Users(String username, String password, Integer status, Set<UserMapping> userMapping, Set<UserRoles> userRoles) {
       this.username = username;
       this.password = password;
       this.status = status;
       this.userMapping = userMapping;
       this.userRoles = userRoles;
    }
    
    public Users(String userName, String password, int status) {
		this.username = userName;
		this.password = password;
		this.status = status;	
	}
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    
    @Column(name="username", length=100)
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    
    @Column(name="password", length=100)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    
    @Column(name="status")
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }

    @OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="users")
    public Set<UserMapping> getUserMapping() {
        return this.userMapping;
    }
    
    public void setUserMapping(Set<UserMapping> userMapping) {
        this.userMapping = userMapping;
    }
    
    @OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="users")
    public Set<UserRoles> getUserRoleses() {
        return this.userRoles;
    }
    
    public void setUserRoleses(Set<UserRoles> userRoleses) {
        this.userRoles = userRoles;
    }
}