package com.bng.core.entity;
// Generated Sep 30, 2013 11:56:12 AM by Hibernate Tools 3.2.1.GA


import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * XmlDetail generated by hbm2java
 */
@Entity
@Table(name="xml_detail")
public class XmlDetail  implements java.io.Serializable {


     private Integer id;
     private String filename;
     private String username;
     private String xmlfile;

    public XmlDetail() {
    }

    public XmlDetail(String filename, String username, String xmlfile) {
       this.filename = filename;
       this.username = username;
       this.xmlfile = xmlfile;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="ID", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    
    @Column(name="filename")
    public String getFilename() {
        return this.filename;
    }
    
    public void setFilename(String filename) {
        this.filename = filename;
    }
    
    @Column(name="username")
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    
    @Column(name="xmlfile", length=65535)
    public String getXmlfile() {
        return this.xmlfile;
    }
    
    public void setXmlfile(String xmlfile) {
        this.xmlfile = xmlfile;
    }




}


